### ISSUE TITLE
Fix issue 

### ISSUE THREAD

**Issue by shado-hackers** [TeamKillerX/RyuzakiLib#124]
Instance created. Preparing to start...
Instance is starting. Propagating network configuration...
[2024-10-05 09:52:06 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2024-10-05 09:52:06 +0000] [8] [INFO] Listening at: http://0.0.0.0:8000 (8)
[2024-10-05 09:52:06 +0000] [8] [INFO] Using worker: sync
[2024-10-05 09:52:06 +0000] [10] [INFO] Booting worker with pid: 10
Instance is healthy. All health checks are passing.
sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /app/.config/sagemaker/config.yaml
/app/.heroku/python/lib/python3.11/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
telethon.crypto.aes - INFO - libssl detected, it will be used for encryption
stability_sdk.client - INFO - Opening channel to grpc.stability.ai:443
stability_sdk.client - INFO - Channel opened to grpc.stability.ai:443
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /workspace/bot.py:72 in <module>                                             │
│                                                                              │
│   69 │   │   │   │   await self.send_message(Config.LOG_CHANNEL, f"**{me.men │
│   70 │   │   │   except:                                                     │
│   71 │   │   │   │   print("Please Make This Is Admin In Your Log Channel")  │
│ ❱ 72 Bot().run()                                                             │
│   73                                                                         │
│                                                                              │
│ /app/.heroku/python/lib/python3.11/site-packages/pyrogram/methods/utilities/ │
│ run.py:81 in run                                                             │
│                                                                              │
│   78 │   │   │   run(coroutine)                                              │
│   79 │   │   else:                                                           │
│   80 │   │   │   if inspect.iscoroutinefunction(self.start):                 │
│ ❱ 81 │   │   │   │   run(self.start())                                       │
│   82 │   │   │   │   run(idle())                                             │
│   83 │   │   │   │   run(self.stop())                                        │
│   84 │   │   │   else:                                                       │
│                                                                              │
│ /app/.heroku/python/lib/python3.11/asyncio/base_events.py:653 in             │
│ run_until_complete                                                           │
│                                                                              │
│    650 │   │   if not future.done():                                         │
│    651 │   │   │   raise RuntimeError('Event loop stopped before Future comp │
│    652 │   │                                                                 │
│ ❱  653 │   │   return future.result()                                        │
│    654 │                                                                     │
│    655 │   def stop(self):                                                   │
│    656 │   │   """Stop running the event loop.                               │
│                                                                              │
│ /workspace/bot.py:53 in start                                                │
│                                                                              │
│   50 │   │   self.models = models                                            │
│   51 │   │   self.db = db                                                    │
│   52 │   async def start(self):                                              │
│ ❱ 53 │   │   await super().start()                                           │
│   54 │   │   me = await self.get_me()                                        │
│   55 │   │   self.mention = me.mention                                       │
│   56 │   │   self.username = me.username                                     │
│                                                                              │
│ /app/.heroku/python/lib/python3.11/site-packages/pyrogram/methods/utilities/ │
│ start.py:75 in start                                                         │
│                                                                              │
│   72 │   │   │   raise                                                       │
│   73 │   │   else:                                                           │
│   74 │   │   │   self.me = await self.get_me()                               │
│ ❱ 75 │   │   │   await self.initialize()                                     │
│   76 │   │   │                                                               │
│   77 │   │   │   return self                                                 │
│   78                                                                         │
│                                                                              │
│ /app/.heroku/python/lib/python3.11/site-packages/pyrogram/methods/auth/initi │
│ alize.py:47 in initialize                                                    │
│                                                                              │
│   44 │   │   if self.is_initialized:                                         │
│   45 │   │   │   raise ConnectionError("Client is already initialized")      │
│   46 │   │                                                                   │
│ ❱ 47 │   │   self.load_plugins()                                             │
│   48 │   │                                                                   │
│   49 │   │   await self.dispatcher.start()                                   │
│   50                                                                         │
│                                                                              │
│ /app/.heroku/python/lib/python3.11/site-packages/pyrogram/client.py:874 in   │
│ load_plugins                                                                 │
│                                                                              │
│    871 │   │   │   if not include:                                           │
│    872 │   │   │   │   for path in sorted(Path(root.replace(".", "/")).rglob │
│    873 │   │   │   │   │   module_path = '.'.join(path.parent.parts + (path. │
│ ❱  874 │   │   │   │   │   module = import_module(module_path)               │
│    875 │   │   │   │   │                                                     │
│    876 │   │   │   │   │   for name in vars(module).keys():                  │
│    877 │   │   │   │   │   │   # noinspection PyBroadException               │
│                                                                              │
│ /app/.heroku/python/lib/python3.11/importlib/__init__.py:126 in              │
│ import_module                                                                │
│                                                                              │
│   123 │   │   │   if character != '.':                                       │
│   124 │   │   │   │   break                                                  │
│   125 │   │   │   level += 1                                                 │
│ ❱ 126 │   return _bootstrap._gcd_import(name[level:], package, level)        │
│   127                                                                        │
│   128                                                                        │
│   129 _RELOADING = {}                                                        │
│ in _gcd_import:1204                                                          │
│ in _find_and_load:1176                                                       │
│ in _find_and_load_unlocked:1147                                              │
│ in _load_unlocked:690                                                        │
│ in exec_module:940                                                           │
│ in _call_with_frames_removed:241                                             │
│                                                                              │
│ /workspace/plugins/gpt.py:93 in <module>                                     │
│                                                                              │
│    90 from pyrogram import *                                                 │
│    91 from pyrogram import Client, filters                                   │
│    92 from pyrogram.types import *                                           │
│ ❱  93 from RyuzakiLib import FullStackDev, GeminiLatest, RendyDevChat        │
│    94 import requests                                                        │
│    95 from datetime import datetime as dt                                    │
│    96                                                                        │
│                                                                              │
│ /app/.heroku/python/lib/python3.11/site-packages/RyuzakiLib/__init__.py:39   │
│ in <module>                                                                  │
│                                                                              │
│    36 from .extreme.quotestk import QouteSticker                             │
│    37 from .extreme.userinfo import TelegramUserInfo                         │
│    38 from .extreme.webshot import WebShotUrl                                │
│ ❱  39 from .fastapi import FastAPISuper                                      │
│    40 from .functions_date import UserDateEstimator                          │
│    41 from .hackertools.alldownloader import AkenoPlus                       │
│    42 from .hackertools.blackbox import Blackbox                             │
│                                                                              │
│ /app/.heroku/python/lib/python3.11/site-packages/RyuzakiLib/fastapi.py:9 in  │
│ <module>                                                                     │
│                                                                              │
│     6 from typing import *                                                   │
│     7                                                                        │
│     8 import requests                                                        │
│ ❱   9 from authlib.integrations.starlette_client import OAuth                │
│    10 from fastapi import FastAPI, HTTPException, Request                    │
│    11 from fastapi.middleware.cors import CORSMiddleware                     │
│    12 from motor.motor_asyncio import AsyncIOMotorClient                     │
╰──────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'authlib'
asyncio - ERROR - Unclosed client session

**Comment by xtsea** [comment]
> Instance created. Preparing to start... Instance is starting. Propagating network configuration... [2024-10-05 09:52:06 +0000] [8] [INFO] Starting gunicorn 20.1.0 [2024-10-05 09:52:06 +0000] [8] [INFO] Listening at: http://0.0.0.0:8000 (8) [2024-10-05 09:52:06 +0000] [8] [INFO] Using worker: sync [2024-10-05 09:52:06 +0000] [10] [INFO] Booting worker with pid: 10 Instance is healthy. All health checks are passing. sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml sagemaker.config INFO - Not applying SDK defaults from location: /app/.config/sagemaker/config.yaml /app/.heroku/python/lib/python3.11/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning) telethon.crypto.aes - INFO - libssl detected, it will be used for encryption stability_sdk.client - INFO - Opening channel to grpc.stability.ai:443 stability_sdk.client - INFO - Channel opened to grpc.stability.ai:443 ╭───────────────────── Traceback (most recent call last) ──────────────────────╮ │ /workspace/bot.py:72 in │ │ │ │ 69 │ │ │ │ await self.send_message(Config.LOG_CHANNEL, f"**{me.men │ │ 70 │ │ │ except: │ │ 71 │ │ │ │ print("Please Make This Is Admin In Your Log Channel") │ │ ❱ 72 Bot().run() │ │ 73 │ │ │ │ /app/.heroku/python/lib/python3.11/site-packages/pyrogram/methods/utilities/ │ │ run.py:81 in run │ │ │ │ 78 │ │ │ run(coroutine) │ │ 79 │ │ else: │ │ 80 │ │ │ if inspect.iscoroutinefunction(self.start): │ │ ❱ 81 │ │ │ │ run(self.start()) │ │ 82 │ │ │ │ run(idle()) │ │ 83 │ │ │ │ run(self.stop()) │ │ 84 │ │ │ else: │ │ │ │ /app/.heroku/python/lib/python3.11/asyncio/base_events.py:653 in │ │ run_until_complete │ │ │ │ 650 │ │ if not future.done(): │ │ 651 │ │ │ raise RuntimeError('Event loop stopped before Future comp │ │ 652 │ │ │ │ ❱ 653 │ │ return future.result() │ │ 654 │ │ │ 655 │ def stop(self): │ │ 656 │ │ """Stop running the event loop. │ │ │ │ /workspace/bot.py:53 in start │ │ │ │ 50 │ │ self.models = models │ │ 51 │ │ self.db = db │ │ 52 │ async def start(self): │ │ ❱ 53 │ │ await super().start() │ │ 54 │ │ me = await self.get_me() │ │ 55 │ │ self.mention = me.mention │ │ 56 │ │ self.username = me.username │ │ │ │ /app/.heroku/python/lib/python3.11/site-packages/pyrogram/methods/utilities/ │ │ start.py:75 in start │ │ │ │ 72 │ │ │ raise │ │ 73 │ │ else: │ │ 74 │ │ │ self.me = await self.get_me() │ │ ❱ 75 │ │ │ await self.initialize() │ │ 76 │ │ │ │ │ 77 │ │ │ return self │ │ 78 │ │ │ │ /app/.heroku/python/lib/python3.11/site-packages/pyrogram/methods/auth/initi │ │ alize.py:47 in initialize │ │ │ │ 44 │ │ if self.is_initialized: │ │ 45 │ │ │ raise ConnectionError("Client is already initialized") │ │ 46 │ │ │ │ ❱ 47 │ │ self.load_plugins() │ │ 48 │ │ │ │ 49 │ │ await self.dispatcher.start() │ │ 50 │ │ │ │ /app/.heroku/python/lib/python3.11/site-packages/pyrogram/client.py:874 in │ │ load_plugins │ │ │ │ 871 │ │ │ if not include: │ │ 872 │ │ │ │ for path in sorted(Path(root.replace(".", "/")).rglob │ │ 873 │ │ │ │ │ module_path = '.'.join(path.parent.parts + (path. │ │ ❱ 874 │ │ │ │ │ module = import_module(module_path) │ │ 875 │ │ │ │ │ │ │ 876 │ │ │ │ │ for name in vars(module).keys(): │ │ 877 │ │ │ │ │ │ # noinspection PyBroadException │ │ │ │ /app/.heroku/python/lib/python3.11/importlib/**init**.py:126 in │ │ import_module │ │ │ │ 123 │ │ │ if character != '.': │ │ 124 │ │ │ │ break │ │ 125 │ │ │ level += 1 │ │ ❱ 126 │ return _bootstrap._gcd_import(name[level:], package, level) │ │ 127 │ │ 128 │ │ 129 _RELOADING = {} │ │ in _gcd_import:1204 │ │ in _find_and_load:1176 │ │ in _find_and_load_unlocked:1147 │ │ in _load_unlocked:690 │ │ in exec_module:940 │ │ in _call_with_frames_removed:241 │ │ │ │ /workspace/plugins/gpt.py:93 in │ │ │ │ 90 from pyrogram import * │ │ 91 from pyrogram import Client, filters │ │ 92 from pyrogram.types import * │ │ ❱ 93 from RyuzakiLib import FullStackDev, GeminiLatest, RendyDevChat │ │ 94 import requests │ │ 95 from datetime import datetime as dt │ │ 96 │ │ │ │ /app/.heroku/python/lib/python3.11/site-packages/RyuzakiLib/**init**.py:39 │ │ in │ │ │ │ 36 from .extreme.quotestk import QouteSticker │ │ 37 from .extreme.userinfo import TelegramUserInfo │ │ 38 from .extreme.webshot import WebShotUrl │ │ ❱ 39 from .fastapi import FastAPISuper │ │ 40 from .functions_date import UserDateEstimator │ │ 41 from .hackertools.alldownloader import AkenoPlus │ │ 42 from .hackertools.blackbox import Blackbox │ │ │ │ /app/.heroku/python/lib/python3.11/site-packages/RyuzakiLib/fastapi.py:9 in │ │ │ │ │ │ 6 from typing import * │ │ 7 │ │ 8 import requests │ │ ❱ 9 from authlib.integrations.starlette_client import OAuth │ │ 10 from fastapi import FastAPI, HTTPException, Request │ │ 11 from fastapi.middleware.cors import CORSMiddleware │ │ 12 from motor.motor_asyncio import AsyncIOMotorClient │ ╰──────────────────────────────────────────────────────────────────────────────╯ ModuleNotFoundError: No module named 'authlib' asyncio - ERROR - Unclosed client session

You can use `pip3 install RyuzakiLib[all]`

**Comment by shado-hackers** [comment]
_RyuzakiLib[all]_ for use it got this problem 

app/.heroku/python/lib/python3.11/site-packages/RyuzakiLib/hackertools/open │
│ ai_api.py:27 in <module>                                                     │
│                                                                              │
│    24 import g4f                                                             │
│    25 import openai                                                          │
│    26 import requests                                                        │
│ ❱  27 from g4f.Provider import Bard                                          │
│    28 from motor.motor_asyncio import AsyncIOMotorClient                     │
│    29                                                                        │
│    30 gpt3_conversation_history = []                                         │
╰──────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'Bard' from 'g4f.Provider' 
(/app/.heroku/python/lib/python3.11/site-packages/g4f/Provider/__init__.py)
asyncio - ERROR - Unclosed client session

**Comment by shado-hackers** [comment]
### **_RyuzakiLib[all]_**  for use it got this problem 

Please fix this problem 

─────────────────────╯
ImportError: cannot import name 'Bard' from 'g4f.Provider'
(/app/.heroku/python/lib/python3.11/site-packages/g4f/Provider/init.py)
asyncio - ERROR - Unclosed client session

**Comment by xtsea** [comment]
> ### **_RyuzakiLib[all]_** for use it got this problem
> Please fix this problem
> 
> ─────────────────────╯ ImportError: cannot import name 'Bard' from 'g4f.Provider' (/app/.heroku/python/lib/python3.11/site-packages/g4f/Provider/init.py) asyncio - ERROR - Unclosed client session

Fix next update

**Comment by shado-hackers** [comment]
Please update pypi package also

**Comment by xtsea** [comment]
> Please update pypi package also

Yes building
